spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
logging:
  file:
    name: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: INFO
server:
  error:
    include-message: always